all:
  children:
    swarm:
    nfsServers:
    nfsClients:

swarm:
  children:
    swarmControllers:
    swarmWorkers:

swarmWorkers:
  hosts:
    192.168.56.12:
    192.168.56.13:
    192.168.56.14:

swarmControllers:
  hosts:
    192.168.56.11:

nfsServers:
  hosts:
    192.168.56.10:

nfsClients:
  hosts:
    192.168.56.11:
    192.168.56.12:
    192.168.56.13:
    192.168.56.14:

